### ISSUE TITLE
Crash related to ptes_vernierEngine_white

### ISSUE THREAD

**Issue by 4yvachok** [PureTilt/ExiledSpace#2]
On game launch crash occurs:

ERROR com.fs.starfarer.combat.CombatMain  - java.lang.RuntimeException: Weapon spec [ptes_vernierEngine_white] not found!
java.lang.RuntimeException: Weapon spec [ptes_vernierEngine_white] not found!
    at com.fs.starfarer.loading.Q.?00000(Unknown Source)
    at com.fs.starfarer.loading.SpecStore.o00000(Unknown Source)
    at com.fs.starfarer.loading.SpecStore.o00000(Unknown Source)
    at com.fs.starfarer.loading.specs.HullVariantSpec.setHullSpec(Unknown Source)
    at com.fs.starfarer.loading.specs.HullVariantSpec.<init>(Unknown Source)
    at com.fs.starfarer.loading.ShipHullSpreadsheetLoader.o00000(Unknown Source)
    at com.fs.starfarer.loading.SpecStore.public(Unknown Source)
    at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)
    at com.fs.state.AppDriver.begin(Unknown Source)
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:750)

**Comment by seVexed** [comment]
Same

**Comment by NoaDel** [comment]
Same, hopefully the author can fix it, I'd love to use this mod

**Comment by Roshag** [comment]
Download mod from releases, not the source code
